sudo: required
services:
- docker


before_install:
- docker build -t hello_world:1.0.0 .

script:
- docker run hello_world:1.0.0

after_success:
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to DOcker hub
  - docker push dineshsonachalam/hello_world:1.0.0
